development:
  adapter: postgresql
  encoding: unicode
  database: demo_test_development
  pool: 5
  username: postgres
  timeout: 5000
  host: "db"
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: posgresql_production
  username: midiabetes
