development:
  adapter: postgresql
  encoding: unicode
  database: demo_test_development
  pool: 5
  username: postgres
  timeout: 5000
  host: "db"
production:
  adapter: postgresql
  encoding: unicode
  database: posgresql_production
  pool: 5
  username: postgres
  timeout: 5000
